// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "SWAPI Translated",
    "version": "1"
  },
  "paths": {
    "/translate/{resource}/{id}": {
      "get": {
        "summary": "translate",
        "description": "",
        "operationId": "translate.get./translate/{resource}/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "resource",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/translate/{resource}": {
      "get": {
        "summary": "translate",
        "description": "",
        "operationId": "translate.get./translate/{resource}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "resource",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/person": {
      "post": {
        "summary": "createPerson",
        "description": "",
        "operationId": "createPerson.post./person",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/DtoCreatePerson"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Person created",
            "schema": {
              "$ref": "#/definitions/ResponseCreatePerson"
            }
          }
        }
      },
      "get": {
        "summary": "getAllPersons",
        "description": "",
        "operationId": "getAllPersons.get./person",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "List of persons",
            "schema": {
              "$ref": "#/definitions/ResponsePersons"
            }
          }
        }
      }
    },
    "/person/{personId}": {
      "get": {
        "summary": "getPerson",
        "description": "",
        "operationId": "getPerson.get./person/{personId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "personId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Person",
            "schema": {
              "$ref": "#/definitions/ResponsePerson"
            }
          }
        }
      },
      "delete": {
        "summary": "deletePerson",
        "description": "",
        "operationId": "deletePerson.delete./person/{personId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "personId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "put": {
        "summary": "updatePerson",
        "description": "",
        "operationId": "updatePerson.put./person/{personId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/DtoUpdatePerson"
            }
          },
          {
            "name": "personId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Person updated",
            "schema": {
              "$ref": "#/definitions/ResponseUpdatePerson"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "IdPerson": {
      "title": "IdPerson",
      "type": "string"
    },
    "Person": {
      "properties": {
        "personId": {
          "$ref": "#/definitions/IdPerson",
          "title": "Person.personId"
        },
        "name": {
          "title": "Person.name",
          "type": "string"
        },
        "height": {
          "title": "Person.height",
          "type": "string"
        },
        "mass": {
          "title": "Person.mass",
          "type": "string"
        },
        "hair_color": {
          "title": "Person.hair_color",
          "type": "string"
        },
        "skin_color": {
          "title": "Person.skin_color",
          "type": "string"
        },
        "eye_color": {
          "title": "Person.eye_color",
          "type": "string"
        },
        "birth_year": {
          "title": "Person.birth_year",
          "type": "string"
        },
        "gender": {
          "title": "Person.gender",
          "type": "string"
        },
        "homeworld": {
          "title": "Person.homeworld",
          "type": "string"
        },
        "films": {
          "items": [],
          "additionalItems": false,
          "minItems": 0,
          "title": "Person.films",
          "type": "array"
        },
        "species": {
          "items": [],
          "additionalItems": false,
          "minItems": 0,
          "title": "Person.species",
          "type": "array"
        },
        "vehicles": {
          "items": [],
          "additionalItems": false,
          "minItems": 0,
          "title": "Person.vehicles",
          "type": "array"
        },
        "starships": {
          "items": [],
          "additionalItems": false,
          "minItems": 0,
          "title": "Person.starships",
          "type": "array"
        },
        "url": {
          "title": "Person.url",
          "type": "string"
        },
        "created": {
          "title": "Person.created",
          "type": "string"
        },
        "edited": {
          "title": "Person.edited",
          "type": "string"
        }
      },
      "required": [
        "personId",
        "name",
        "height",
        "mass",
        "hair_color",
        "skin_color",
        "eye_color",
        "birth_year",
        "gender",
        "homeworld",
        "films",
        "species",
        "vehicles",
        "starships",
        "url",
        "created",
        "edited"
      ],
      "additionalProperties": false,
      "title": "Person",
      "type": "object"
    },
    "ResponseCreatePerson": {
      "properties": {
        "error": {
          "title": "ResponseCreatePerson.error",
          "nullable": true
        },
        "data": {
          "$ref": "#/definitions/IdPerson",
          "title": "ResponseCreatePerson.data"
        }
      },
      "required": [
        "error",
        "data"
      ],
      "additionalProperties": false,
      "title": "ResponseCreatePerson",
      "type": "object"
    },
    "DtoCreatePerson": {
      "properties": {
        "name": {
          "title": "DtoCreatePerson.name",
          "type": "string"
        },
        "height": {
          "title": "DtoCreatePerson.height",
          "type": "string"
        },
        "mass": {
          "title": "DtoCreatePerson.mass",
          "type": "string"
        },
        "hair_color": {
          "title": "DtoCreatePerson.hair_color",
          "type": "string"
        },
        "skin_color": {
          "title": "DtoCreatePerson.skin_color",
          "type": "string"
        },
        "eye_color": {
          "title": "DtoCreatePerson.eye_color",
          "type": "string"
        },
        "birth_year": {
          "title": "DtoCreatePerson.birth_year",
          "type": "string"
        },
        "gender": {
          "title": "DtoCreatePerson.gender",
          "type": "string"
        }
      },
      "required": [
        "name",
        "height",
        "mass",
        "hair_color",
        "skin_color",
        "eye_color",
        "birth_year",
        "gender"
      ],
      "additionalProperties": false,
      "title": "DtoCreatePerson",
      "type": "object"
    },
    "DtoUpdatePerson": {
      "properties": {
        "name": {
          "title": "DtoUpdatePerson.name",
          "type": "string"
        },
        "height": {
          "title": "DtoUpdatePerson.height",
          "type": "string"
        },
        "mass": {
          "title": "DtoUpdatePerson.mass",
          "type": "string"
        },
        "hair_color": {
          "title": "DtoUpdatePerson.hair_color",
          "type": "string"
        },
        "skin_color": {
          "title": "DtoUpdatePerson.skin_color",
          "type": "string"
        },
        "eye_color": {
          "title": "DtoUpdatePerson.eye_color",
          "type": "string"
        },
        "birth_year": {
          "title": "DtoUpdatePerson.birth_year",
          "type": "string"
        },
        "gender": {
          "title": "DtoUpdatePerson.gender",
          "type": "string"
        }
      },
      "required": [
        "name",
        "height",
        "mass",
        "hair_color",
        "skin_color",
        "eye_color",
        "birth_year",
        "gender"
      ],
      "additionalProperties": false,
      "title": "DtoUpdatePerson",
      "type": "object"
    },
    "ResponseUpdatePerson": {
      "properties": {
        "error": {
          "title": "ResponseUpdatePerson.error",
          "nullable": true
        },
        "data": {
          "title": "ResponseUpdatePerson.data",
          "type": "boolean"
        }
      },
      "required": [
        "error",
        "data"
      ],
      "additionalProperties": false,
      "title": "ResponseUpdatePerson",
      "type": "object"
    },
    "ResponsePersons": {
      "properties": {
        "error": {
          "title": "ResponsePersons.error",
          "nullable": true
        },
        "data": {
          "items": {
            "$ref": "#/definitions/Person",
            "title": "ResponsePersons.data.[]"
          },
          "title": "ResponsePersons.data",
          "type": "array"
        }
      },
      "required": [
        "error",
        "data"
      ],
      "additionalProperties": false,
      "title": "ResponsePersons",
      "type": "object"
    },
    "ResponsePerson": {
      "properties": {
        "error": {
          "title": "ResponsePerson.error",
          "nullable": true
        },
        "data": {
          "$ref": "#/definitions/Person",
          "title": "ResponsePerson.data"
        }
      },
      "required": [
        "error",
        "data"
      ],
      "additionalProperties": false,
      "title": "ResponsePerson",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https",
    "http"
  ]
};